version: "3.3"
services:
    wordpress:
        image: hendrik44/infinitewp-docker
        hostname: infinitewp
        container_name: infinitewp
        cap_drop:
            - NET_ADMIN
            - SYS_ADMIN
        tmpfs:
            - /run
            - /tmp
        depends_on:
            - mysql
        restart: always
        # ports:
        #     - 127.0.0.1:80:80
        links:
            - mysql
        labels:
            - "traefik.enable=true"
            - "traefik.backend=infinitewp-apache"
            - "traefik.frontend.rule=Host:localhost" # for local testing
            #- "traefik.frontend.rule=Host:test.de" # production
            - "traefik.docker.network=proxy"
            - "traefik.protocol=http"
            - "traefik.port=80"
            - "traefik.frontend.passHostHeader=true"
            - frontend.whiteList.useXForwardedFor=true
            - "traefik.frontend.headers.browserXSSFilter=true"
            - "traefik.frontend.headers.customBrowserXSSValue=X-XSS-Protection: 1; mode=block"
        volumes:
          - iwp-data:/var/www/html
        networks:
          - internal
          - proxy

    mysql:
        image: mariadb
        hostname: database
        container_name: database
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mydb
          MYSQL_USER: mydb
          MYSQL_PASSWORD: password
        labels:
            - traefik.enable=false
        volumes:
          - db-data:/var/lib/mysql
        restart: always
        networks:
          - internal

    adminer:
        image: adminer:4.6.3-standalone
        read_only: true
        volumes:
          - /tmp
        labels:
          - traefik.backend=adminer
          - traefik.frontend.rule=Host:adminer.localhost
          - traefik.docker.network=proxy
          - traefik.port=8080
          - "traefik.frontend.passHostHeader=true"
          - "traefik.frontend.headers.browserXSSFilter=true"
          # - traefik.frontend.headers.contentSecurityPolicy=VALUE
          - "traefik.frontend.headers.customBrowserXSSValue=X-XSS-Protection: 1; mode=block"
        # ports:
        #   - "127.0.0.1:8080:8080"
        networks:
          - internal
          - proxy
        depends_on:
          - mysql
        links:
          - mysql

    traefik:
      image: traefik
      hostname: traefik
      container_name: traefik
      command: --api --docker
      ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml:ro
        - ./traefik/acme.json:/acme.json
      networks:
        - proxy
            
volumes:
  iwp-data:
  db-data:

networks:
  proxy:
    external: true
  internal:
    external: false
  